import type { Metadata } from 'next'

import './globals.css'
import { montserrat } from './fonts'

export const metadata: Metadata = {
    title: 'Personal Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                {children}
                <div className="noise-overlay" />
            </body>
        </html>
    )
}
